### ISSUE TITLE
Support secure websockets (wss)

### ISSUE THREAD

**Issue by ecthiender** [ecthiender/py-graphql-client#1]
Currently wss does not work. Add support for wss.

**Comment by SalmonMode** [comment]
After using this for a little bit, and talking with someone far more familiar with GraphQL than me, it looks like not being able to do `wss` is a result of not including this header when making the initial connection:

```
"Sec-WebSocket-Protocol: graphql-ws"
```

I think including this by default should solve the problem.

**Comment by ecthiender** [comment]
@SalmonMode thanks for the PR. I will test this out and then merge it. Probably won't be today, but I will get to it as soon as I can.
