### ISSUE TITLE
How can I pass authentication header ?

### ISSUE THREAD

**Issue by username7171** [ecthiender/py-graphql-client#12]
referencing  https://developer.github.com/v4/guides/using-the-explorer/
  

__In the Key field, enter Authorization. In the Value field, enter Bearer <token>, where <token> is your generated OAuth token__

How could we pass the Authorization header in this library?

**Comment by JasonAtallah** [comment]
@AronWater the subscribe method can take in a 'headers' arg.

e.g.
`ws.subscribe(query, callback=callback, headers=headers`

**Comment by ecthiender** [comment]
@AronWater as @JasonAtallah mentioned, you can pass headers to either the `subscribe` method or `query` method as `ws.query(query, headers=headers)` or `ws.subscribe(query, callback=mycallback, headers=headers)`.

So `Authorization` header example:

```python
myheaders = {'Authorization': 'Bearer xxxxxx'}

query = ...

def my_callback(msg_id, data):
  pass

ws.subscribe(query, callback=my_callback, headers=my_headers)
```

I am closing this issue. If you face any issues, feel free to reopen the issue and we can troubleshoot.
