### ISSUE TITLE
Can you give an SSL example?

### ISSUE THREAD

**Issue by jamessmith-decisionlab** [ecthiender/py-graphql-client#13]
If I connect to a URL of the form `wss://...` I get an SSL error, but is SSL supported? I guess you need to provide a way to pass a native SSL context?

**Comment by ecthiender** [comment]
Hey @jamessmith-decisionlab my apologies for the extreme delay in responding.

The library works with SSL out of the box. If you use the `wss://` prefix it should be fine. Does your server use a self-signed SSL certificate?

Can you paste the exact errors you get? That should help.

**Comment by djalbat** [comment]
Thank you and no worries about the late reply. I'm not longer working on that contract so there's no real need for me to pursue this issue. However, I'm glad to hear that you support SSL. I'll bear it in mind.

**Comment by ecthiender** [comment]
@djalbat thanks for your response! I will close this issue. If you encounter any problems in the future, don't hesitate to open an issue.
