### ISSUE TITLE
how to use subscriptions ?

### ISSUE THREAD

**Issue by bharatpk0** [ecthiender/py-graphql-client#15]
HI , 

THIS MODULES HELPS US TO SUBSCRIPT TO A SERVICE , AFTER SUBSCRIPTION WE NEED TO KEEP TO CONNECTION OPEN TO RECEIVE POST REQUESTS WHEN EVER SERVER SENDS US , HOW DO WE HANDLE THAT ?

**Comment by ecthiender** [comment]
You pass a callback function to the start method. The callback function is called whenever new data arrives. So you should write code inside your callback function in such a way such that it handles new data coming from the server every time it is called. You can stop the subscription outside the callback function using the subscription id.

See the code example here: https://github.com/ecthiender/py-graphql-client#setup-subscriptions-super-easily

Let me know if this helps or you have more questions

**Comment by ecthiender** [comment]
@bharatpk0 I am closing this issue. But you can ask more questions, if you have, on this thread. (Feel free to re-open if you see any issue).
