### ISSUE TITLE
Feedback: Multiple subscription callbacks in one thread

### ISSUE THREAD

**Issue by TimGuiteDiamond** [ecthiender/py-graphql-client#19]
Hey, obviously an issue probably isn't the best place to put this but there aren't many other feedback mechanisms on Github!

Just wanted to say thanks for your work! I mentioned before about more efficiently adding multiple callbacks to a single thread, was going to look at it today but it seems that your changes in e48ea36d837ec740f0a723979b658835b1d1e70f have already addressed it!

From the tests I ran this morning it seems to be working well, with only one thread handling many separate subscriptions. I will test a bit further and put feedback here if that's alright?

Let me know if there are any other tasks you would like helping with for this package 😄

**Comment by ecthiender** [comment]
@TimGuiteDiamond thanks for the issue. An issue is a pretty good place to discuss on github, I think, so its perfectly alright!

Please do feel free to put your feedback here :) I have already published the latest changes in a pre-release version (https://pypi.org/project/py-graphql-client/0.1.1b2/) [1], you can try it out. I'm planning to release a stable version after doing some more testing. I must admit, the library had some rough edges, but with the latest changes, hopefully, everything should work.

I think using this in a non-trivial project and providing feedback regarding the API, UX, bugs and literally anything else would be quite a bit of help. Apart from that feel free to contribute anything, especially if you have anything specific in mind.


[1]: 
```
pip install py-graphql-client==0.1.1b2
```

**Comment by TimGuiteDiamond** [comment]
To follow up on this, I installed the beta to my project today and it worked how I had hoped it would! Similar (slightly better) performance than what I had achieved from hacking the previous version 😄 

So quite happy with this!

**Comment by ecthiender** [comment]
@TimGuiteDiamond thanks for your kind words! :) I have published a stable version now : https://pypi.org/project/py-graphql-client/ (v0.1.1) .

Let me know if any other features you would like. :)

**Comment by ecthiender** [comment]
@TimGuiteDiamond I'm closing this. Feel free to open other issues if you have any feedback.
