### ISSUE TITLE
Unable to import module

### ISSUE THREAD

**Issue by weeotch** [ecthiender/py-graphql-client#23]
I'm running Python 3.5.2 on Ubuntu.  Attempting to import GraphQLClient throws the following:

`Traceback (most recent call last):
  File "this_one.py", line 1, in <module>
    from graphql_client import GraphQLClient
  File "/path/lib/python3.5/site-packages/graphql_client/__init__.py", line 102
    err = f'Protocol Violation.\nExpected "id" in {msg}, but could not find.'
                                                                            ^
SyntaxError: invalid syntax
`

Looking into Python3 f-strings, it looks like they aren't supported until 3.6, but your docs state this lib just requires >= 3.4.

**Comment by ecthiender** [comment]
@weeotch you are right. This library now uses f-strings (from recent releases). I forgot to update the docs :(  I will update the docs. But will you be able to run Python 3.6?

If not, I'll see what I can do to support Python 3.5

Let me know! :)
