### ISSUE TITLE
How to handle exception when the client lost connection .

### ISSUE THREAD

**Issue by bueltan** [ecthiender/py-graphql-client#26]
Hi !, maybe my question is out the range of this library , but i need handle exception when the client lost connection whit the server for any reason,  and don't found documentation above this.

**Comment by AleMuzzi** [comment]
I fixed it in pull request #37 , you can use my fork till is not merged https://github.com/AleMuzzi/py-graphql-client

**Comment by ecthiender** [comment]
Thanks for reporting. And thanks to @AleMuzzi for fixing it. It is now released in [0.1.2](https://pypi.org/project/py-graphql-client/0.1.2/). Please upgrade your package to get the fixed version pip install py-graphql-client==0.1.2.
