### ISSUE TITLE
Subscription parameters wrapped in "headers" attribute

### ISSUE THREAD

**Issue by jasonkatz** [ecthiender/py-graphql-client#28]
Hi,

I'm looking to pass some auth information in subscription parameters, but the payload for the connection initialization wraps the headers in a nested `headers` attribute ([here](https://github.com/ecthiender/py-graphql-client/blob/master/graphql_client/__init__.py#L149), instead of passing them as-is.

This assumes that the target server looks inside a `headers` property on the incoming parameters - different servers handle these payloads differently. Some added flexibility to the client library will make it much more versatile and usable against various servers.

I will submit a quick PR to address this, but looking forward to hearing any thoughts!

**Comment by ecthiender** [comment]
Hi @jasonkatz , sorry for extremely slow response.

This library follows the [Apollo Websocket protocol](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md). (Although now deprecated). The target server you're dealing with should also support the same Apollo Websocket protocol for this client library to work.

I'm closing this issue, but feel free to ask more questions or re-open it.
