### ISSUE TITLE
stop_subscribe has threading issues/exceptions

### ISSUE THREAD

**Issue by BharathaAravind** [ecthiender/py-graphql-client#7]
Adding a few checks to stop_subscribe to prevent threading issues when stop_subscribe is called explicitly.

**Comment by BharathaAravind** [comment]
https://github.com/ecthiender/py-graphql-client/pull/6

**Comment by ecthiender** [comment]
@BharathaAravind can you explain the threading issues ?

**Comment by ecthiender** [comment]
e48ea36d837ec740f0a723979b658835b1d1e70f fixes this issue.
